export const SAMPLE_DOCUMENTS = [
  {
    title: "TEST CASE 1: The 'Silicon Valley' Infinite IP & Non-Compete",
    content: `11. INTELLECTUAL PROPERTY AND INVENTIONS ASSIGNMENT
11.1 Definition of Intellectual Property. For the purposes of this Agreement, "Intellectual Property" shall mean and include any and all inventions, discoveries, designs, developments, methods, modifications, improvements, processes, algorithms, databases, computer programs, formulae, techniques, trade secrets, graphics or images, audio or visual works, and other works of authorship (whether or not patentable or copyrightable or subject to trademark, trade secret, or other intellectual property protection) that are made, conceived, developed, or reduced to practice by the Employee, either alone or jointly with others.
11.2 Infinite Assignment. The Employee hereby irrevocably assigns, transfers, and conveys to the Company (and its successors and assigns) all right, title, and interest in and to any and all Intellectual Property that the Employee creates, develops, or conceives during the term of their employment. This assignment shall apply universally, regardless of whether the Intellectual Property was created during regular business hours or after-hours, and irrespective of whether company equipment, facilities, or resources were utilized in its creation. This includes any side projects, open-source contributions, or personal ventures conceived by the Employee during the employment period, which shall be deemed the exclusive property of the Company.
11.3 Moral Rights Waiver. To the maximum extent permitted by applicable law, the Employee hereby waives and agrees never to assert any and all "moral rights," or any rights of paternity, integrity, disclosure, and withdrawal, or any other rights that may be known as or referred to as moral rights, in relation to any Intellectual Property assigned to the Company.

12. POST-EMPLOYMENT RESTRICTIVE COVENANTS
12.1 Global Non-Competition. The Employee acknowledges that the Company operates on a global scale. Therefore, the Employee agrees that during the term of their employment and for a continuous, uninterrupted period of thirty-six (36) months following the termination of employment (whether voluntary or involuntary, and regardless of cause), the Employee shall not, directly or indirectly, engage in, consult for, advise, invest in, or otherwise participate in any business, enterprise, or entity that competes with the Company. "Competition" shall be defined broadly to include any technology sector, software development, data analytics, or e-commerce operations.
12.2 Geographic Scope. Given the digital nature of the Company's business, this non-competition covenant shall apply globally, encompassing all countries, territories, and jurisdictions where the internet is accessible. The Employee expressly agrees that this geographic scope is reasonable and necessary to protect the Company's legitimate business interests and trade secrets.
12.3 Liquidated Damages. In the event of a breach of Section 12, the Employee agrees to pay the Company liquidated damages in the amount of $500,000 USD, or the equivalent in local currency, without the need for the Company to prove actual damages. This remedy shall be in addition to, and not in lieu of, injunctive relief.`
  },
  {
    title: "TEST CASE 2: The 'Zero Privacy' Device Monitoring & Liability Trap",
    content: `8. DEVICE SURVEILLANCE AND DATA PRIVACY
8.1 Blanket Consent to Monitoring. The Employee understands and expressly agrees that the Company utilizes advanced endpoint detection, monitoring, and surveillance software. The Employee hereby grants the Company irrevocable, perpetual, and unconditional consent to monitor, record, log, and analyze all activities conducted on any device used for work purposes. This includes, but is not limited to, company-issued laptops, smartphones, and tablets, as well as any personal devices (Bring Your Own Device - BYOD) that access the Company's network, email servers, or communication platforms (e.g., Slack, Teams).
8.2 Scope of Interception. The monitoring authorized herein encompasses the interception of all digital communications, including personal emails, private direct messages, keystroke logging, browser history, screen recording, and the accessing of local file systems on the aforementioned devices. The Employee waives any expectation of privacy regarding any data, file, or communication transmitted through or stored on these devices.
8.3 Biometric Data. The Employee agrees to submit to biometric tracking, including facial recognition scans via webcams and fingerprint logging, to verify presence and engagement during remote working hours. The Company reserves the right to share this biometric data with third-party vendors and international subsidiaries at its sole discretion, without further notification to the Employee.

9. UNLIMITED FINANCIAL LIABILITY AND INDEMNIFICATION
9.1 Absolute Liability for Breaches. The Employee acknowledges that safeguarding the Company's data is of paramount importance. The Employee assumes full, absolute, and unlimited financial liability for any data breach, security incident, or unauthorized access event that originates from their network credentials, device access, or negligent actions.
9.2 Indemnification Obligation. The Employee agrees to defend, indemnify, and hold harmless the Company, its directors, officers, shareholders, and affiliates from and against any and all claims, damages, liabilities, costs, and expenses (including, without limitation, exorbitant legal fees, regulatory fines under the GDPR or DPDP Act, and settlement amounts) arising out of or related to any cybersecurity failure attributed to the Employee.
9.3 Wage Garnishment. The Employee expressly authorizes the Company to garnish, withhold, or seize any unpaid wages, bonuses, stock options, or severance packages to satisfy any financial obligations arising under Section 9.2, without the requirement of a prior court order or judicial decree.`
  },
  {
    title: "TEST CASE 3: The 'At-Will' Instant Termination & Clawback",
    content: `15. TERMINATION AT WILL AND WITHOUT CAUSE
15.1 Arbitrary Dismissal. The Employee's employment with the Company is entered into voluntarily and is strictly "at-will." This means that the Company reserves the absolute, unilateral right to terminate the employment relationship at any time, with or without cause, with or without performance warnings, and without any prior notice whatsoever. The Employee expressly waives any statutory right to notice periods or severance protections that might otherwise be afforded by local labor laws, including but not limited to the Industrial Disputes Act.
15.2 Immediate Offboarding. Upon notification of termination, the Employee must immediately surrender all Company property and vacate the premises (or disconnect from remote networks). The Company may forcibly terminate access to all systems without allowing the Employee time to retrieve personal files or data.

16. COMPENSATION CLAWBACK PROVISIONS
16.1 Bonus and Equity Forfeiture. In the event of termination for any reason (including layoffs or company restructuring), the Employee shall immediately forfeit any unvested equity, pending bonuses, or deferred compensation.
16.2 Retroactive Clawback. If the Company determines, at its sole and absolute discretion, that the Employee's performance was subpar or detrimental to the Company's culture during the trailing twelve (12) months prior to termination, the Company reserves the right to retroactively clawback up to 50% of the Employee's base salary paid during that period. The Employee agrees to remit these funds to the Company within fifteen (15) days of receiving a clawback demand.

17. WAIVER OF LEGAL RECOURSE
17.1 Forced Arbitration. Any dispute, controversy, or claim arising out of or relating to this employment agreement, including alleged wrongful termination or harassment, shall be settled exclusively by binding arbitration. The arbitrator shall be chosen solely by the Company. The Employee waives any right to bring a civil lawsuit or participate in a class-action lawsuit against the Company.
17.2 Jurisdiction. The arbitration shall take place in a jurisdiction selected by the Company, potentially overseas, and the Employee shall bear all costs of travel and initial arbitration filing fees.`
  }
];
